name: ubuntu-cve-status
base: core18
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Analyse and report CVE status using oscap for a Ubuntu machine
description: |
  Simple wrapper around oscap to leverage the OVAL data published by the
  Ubuntu Security Team to generate a report listing the status of CVEs
  applicable to a Ubuntu machine

grade: devel
confinement: strict

plugs:
  apt-cache:
    interface: system-files
    read:
      - /var/lib/snapd/hostfs/var/cache/apt
  dpkg-data:
    interface: system-files
    read:
      - /usr/share/dpkg # required to read cputable etc

layout:
  /usr/bin/dpkg:
    bind-file: $SNAP/usr/bin/dpkg
  /etc/dpkg/dpkg.cfg:
    bind-file: $SNAP/dpkg.cfg
  /etc/wgetrc:
    bind-file: $SNAP/etc/wgetrc
  /usr/share/openscap:
    bind: $SNAP/usr/share/openscap
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/openscap:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/openscap

apps:
  ubuntu-cve-status:
    command: ubuntu-cve-status
    plugs:
      - network
      - desktop # required to launch browser to view report
      - apt-cache
      - dpkg-data
    environment:
      # need to tell apt to look under /var/lib/snapd/hostfs via a custom
      # apt configuration
      APT_CONFIG: /snap/$SNAP_NAME/current/apt.conf


parts:
  ubuntu-cve-status:
    plugin: dump
    source: .
    organize:
      ubuntu-cve-status: /usr/bin/ubuntu-cve-status

    stage-packages:
      - libopenscap8
      - wget
      - bzip2
